package com.dankai.retrofit.loader;
/*
 *  项目名:    Practice
 *  包名：     com.dankai.loader
 *  文件名:    LoaderStyleEnum
 *  创建者:    WK
 *  时间：     2019/8/21 11:09
 *  描述：     TODO
 */

@SuppressWarnings("ALL")
public enum LoaderStyleEnum {
    BALL_PULSE_INDICATOR,
    BALL_GRID_PULSE_INDICATOR,
    BALL_CLIP_ROTATE_INDICATOR,
    BALL_CLIP_ROTATE_PULSE_INDICATOR,
    SQUARE_SPIN_INDICATOR,
    BALL_CLIP_ROTATE_MULTIPLE_INDICATOR,
    BALL_PULSE_RISE_INDICATOR,
    BALL_ROTATE_INDICATOR,
    CUBE_TRANSITION_INDICATOR,
    BALL_ZIG_ZAG_INDICATOR,
    BALL_ZIG_ZAG_DEFLECT_INDICATOR,
    BALL_TRIANGLE_PATH_INDICATOR,
    BALL_SCALE_INDICATOR,
    LINE_SCALE_INDICATOR,
    LINE_SCALE_PARTY_INDICATOR,
    BALL_SCALE_MULTIPLE_INDICATOR,
    BALL_PULSE_SYNC_INDICATOR,
    BALL_BEAT_INDICATOR,
    LINE_SCALE_PULSE_OUT_INDICATOR,
    LINE_SCALE_PULSE_OUT_RAPID_INDICATOR,
    BALL_SCALE_RIPPLE_INDICATOR,
    BALL_SCALE_RIPPLE_MULTIPLE_INDICATOR,
    BALL_SPIN_FADE_LOADER_INDICATOR,
    LINE_SPIN_FADE_LOADER_INDICATOR,
    TRIANGLE_SKEW_SPIN_INDICATOR,
    PACMAN_INDICATOR,
    BALL_GRID_BEAT_INDICATOR,
    SEMI_CIRCLE_SPIN_INDICATOR,
}
